version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-cursos
    environment:
      MYSQL_ROOT_PASSWORD: igor
      MYSQL_DATABASE: cursos
      MYSQL_USER: igor
      MYSQL_PASSWORD: igor
    ports:
      - "3306:3306"
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: igor
#      MONGO_INITDB_ROOT_PASSWORD: igor
#    ports:
#      - "27017:27017"